# Use the official Node.js image as a base
FROM node:14-alpine
 
# Set the working directory
WORKDIR /app
 
# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the entire app to the container
COPY . .
 
# Expose the port your app will run on
EXPOSE 3000
 
# Start the React Native app
CMD ["npm", "start"]